# Generated by Django 4.2.1 on 2023-06-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='verification_code',
            field=models.CharField(blank=True, null=True, verbose_name='email_verification_code'),
        ),
    ]
