# Generated by Django 4.2.1 on 2023-05-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, verbose_name='heading')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('content', models.TextField(verbose_name='content')),
                ('img', models.ImageField(upload_to='blog/', verbose_name='preview')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date')),
                ('is_published', models.BooleanField(default=True, verbose_name='is_published')),
                ('views', models.IntegerField(verbose_name='views number')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
