# Generated by Django 4.2.1 on 2023-06-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_heading_alter_blog_slug_alter_blog_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='views number'),
        ),
    ]
