# Generated by Django 4.2.1 on 2023-06-27 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('set_published', 'can publish/unpublish')], 'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
    ]
