# Generated by Django 4.2.1 on 2023-05-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, default='media/device.jpeg', null=True, upload_to='media/', verbose_name='product_img'),
        ),
    ]
