# Generated by Django 4.2.1 on 2023-06-13 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_product_price_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='item_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='item_descr')),
                ('price', models.IntegerField(verbose_name='item_price')),
                ('stock', models.IntegerField(verbose_name='item_stock')),
                ('img', models.ImageField(upload_to='media/items/', verbose_name='item_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product_name')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
            },
        ),
    ]
