# Generated by Django 4.2.1 on 2023-06-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_product_slug_alter_product_id_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='is_active'),
        ),
    ]
