# Generated by Django 4.2.1 on 2023-06-13 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='version_name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='version_descr')),
                ('price', models.IntegerField(verbose_name='version_price')),
                ('stock', models.IntegerField(verbose_name='version_stock')),
                ('img', models.ImageField(upload_to='media/versions/', verbose_name='version_img')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='product_name')),
            ],
            options={
                'verbose_name': 'version',
                'verbose_name_plural': 'versions',
            },
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
