# Generated by Django 4.2.1 on 2023-06-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_remove_version_is_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='is_active',
            field=models.BooleanField(verbose_name='is_active'),
        ),
    ]
