# Generated by Django 4.2.1 on 2023-06-26 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_published', 'can publish/make unpublished')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
    ]
